# -*- coding: utf-8 -*-
"""VideoSummaryApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2-GrikYVS3Ddk74xNiDt3VFRD8KyT9y
"""

'''
!pip install sentencepiece
!pip install streamlit
!pip install pyngrok
'''

import streamlit
import youtube_transcript_api
from youtube_transcript_api import YouTubeTranscriptApi
import nltk
import re
import numpy as np
from nltk.corpus import stopwords
import sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import sent_tokenize
nltk.download('punkt')
from transformers import pipeline
from transformers import T5Tokenizer, T5ForConditionalGeneration
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

st.title("YouTube Video Summarization App")

# Button to perform action
if st.button('Summarize'):
    if user_input:
        with st.spinner('Generating video summary...'):
            try:
                # Attempt to generate summary
                summary_text = youtube_get.youtube_sub()
                st.write(summary_text)
            except Exception as e:
                # Handle any errors that occur
                st.error(f"An error occurred: {e}")
    else:
        st.write("Please enter a valid YouTube link")



# Button to perform action
#if st.button('Summarize'):
#    if user_input:
#        with st.spinner('Generating summary video...'):
#            summary_text = youtube_get.youtube_sub()
#            st.write(summary_text)
#    else:
#        st.write("Please enter a valid YouTube link")

